from app.schemas.template import TemplateOut

TEMPLATES: list[TemplateOut] = [
    TemplateOut(
        key="youtube_thumbnail",
        name="YouTube Thumbnail",
        style="Premium Cinematic",
        intent="Curiosity",
        layout="Hero Focus",
        typography="Bold Display",
        spacing="Compact",
        aspect_ratio="16:9",
        subject_hint="Close-up of the presenter reacting, with the video's central subject framed behind them.",
    ),
    TemplateOut(
        key="linkedin_banner",
        name="LinkedIn Banner",
        style="Swiss",
        intent="Trust",
        layout="Asymmetrical",
        typography="Corporate Professional",
        spacing="Generous White Space",
        aspect_ratio="16:9",
        subject_hint="Professional headshot or brand mark aligned to one side with a clear value statement.",
    ),
    TemplateOut(
        key="instagram_post",
        name="Instagram Post",
        style="Editorial",
        intent="Bold",
        layout="Centered",
        typography="Modern Sans Serif",
        spacing="Balanced",
        aspect_ratio="1:1",
        subject_hint="Single hero product or subject centered with a short punchy headline.",
    ),
    TemplateOut(
        key="instagram_story",
        name="Instagram Story",
        style="Minimalist",
        intent="Urgency",
        layout="Hero Focus",
        typography="Bold Display",
        spacing="Compact",
        aspect_ratio="9:16",
        subject_hint="Full-bleed vertical shot of the subject with a time-limited offer callout.",
    ),
    TemplateOut(
        key="business_ad",
        name="Business Advertisement",
        style="Swiss",
        intent="Trust",
        layout="Grid Based",
        typography="Corporate Professional",
        spacing="Balanced",
        aspect_ratio="4:5",
        subject_hint="Product or service shot with supporting proof points arranged in a grid.",
    ),
    TemplateOut(
        key="real_estate_poster",
        name="Real Estate Poster",
        style="Premium Cinematic",
        intent="Luxury",
        layout="Magazine Style",
        typography="Editorial Serif",
        spacing="Generous White Space",
        aspect_ratio="4:5",
        subject_hint="Exterior or interior property shot at golden hour with address and price callout.",
    ),
    TemplateOut(
        key="festival_greeting",
        name="Festival Greeting",
        style="Editorial",
        intent="Luxury",
        layout="Centered",
        typography="Editorial Serif",
        spacing="Balanced",
        aspect_ratio="1:1",
        subject_hint="Festive motif relevant to the occasion with a warm greeting headline.",
    ),
    TemplateOut(
        key="product_promotion",
        name="Product Promotion",
        style="Brutalist",
        intent="Bold",
        layout="Hero Focus",
        typography="Bold Display",
        spacing="Compact",
        aspect_ratio="1:1",
        subject_hint="Product shot isolated on a strong background color with a bold discount callout.",
    ),
]


def get_template(key: str) -> TemplateOut | None:
    return next((t for t in TEMPLATES if t.key == key), None)
